sudo: false

language: python

python:
  - "2.6"
  - "2.7"

virtualenv:
    system_site_packages: true

before_install:
  - sudo SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - sudo rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get install python-numpy
  - sudo apt-get install python-opencv
    
install: "pip install -r requirements.txt"

script: nosetests
