language: python

python:
  - "2.7"

env:
  - PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7

addons:
  apt:
    packages:
    - libopencv-dev
    - python-opencv
    
install: "pip install -r requirements.txt"

script: nosetests
